
    datasource:
      url: jdbc:mysql://localhost:3306/tlias?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456



      mybatis:
        mapper-locations: classpath*:mapper/*.xml
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

